# -*- coding: utf-8 -*-
"""Copy of Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZXcA9lv0nJbzW6weccbJB2hpLseJWQq-
"""

CPU_O3 = [
0.001000,
0.002000,
0.002000,
0.002000,
0.003000,
0.006000,
0.016000,
0.067000,
0.400000,
2.064000
]

CPU = [
0.002000,
0.002000,
0.002000,
0.002000,
0.004000,
0.010000,
0.035000,
0.179000,
0.816000,
3.718000,
]

CUBLAS = [
240.576035,
241.298752,
242.172287,
243.732742,
239.544128,
241.343964,
244.608612,
240.567841,
239.189758,
241.613403
]

GPU = [
0.230464,
0.227840,
0.225984,
0.227296,
0.240032,
0.242816,
0.250944,
0.273152,
0.422816,
1.092480
]
X = [1,2,3,4,5,6,7,8,9,10]
# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline


plt.plot(X,GPU , marker ='o', label='GPU')
# plt.plot(X, CUBLAS, marker ='o', label= 'CUBLAS' )
plt.plot(X, CPU_O3, marker ='o', label= 'CPU_O3')
plt.plot(X, CPU,marker ='o' , label= 'CPU')
plt.legend()
plt.xlabel("Log base 2 of matrix dimension")
plt.ylabel("Time in (ms)")
plt.savefig('comparision.svg', dpi=300)
plt.show()

